package app.aaps.plugins.aps.openAPSAIMI.effects

import app.aaps.core.interfaces.resources.TextResolver
import app.aaps.core.interfaces.utils.DateUtil
import app.aaps.core.interfaces.utils.TimeDiff
import app.aaps.plugins.aps.openAPSAIMI.aimiWallClockMs

/**
 * Clock stored on the reactivity learner. The cold file read does not format dates.
 * [now] is the same wall clock the rest of the iOS tick uses.
 */
internal class LearnerColdClock : DateUtil {
    private fun unused(): Nothing = error("LearnerColdClock: learner files do not format dates")

    override fun fromISODateString(isoDateString: String): Long = unused()
    override fun toISOString(date: Long): String = unused()
    override fun toISOAsUTC(timestamp: Long): String = unused()
    override fun toISONoZone(timestamp: Long): String = unused()
    override fun secondsOfTheDayToMillisecondsOfHoursAndMinutes(seconds: Int): Long = unused()
    override fun secondsOfTheDayToMilliseconds(seconds: Int): Long = unused()
    override fun toSeconds(hhColonMm: String): Int = unused()
    override fun dateString(mills: Long): String = unused()
    override fun dateStringRelative(mills: Long, rh: TextResolver): String = unused()
    override fun dateStringShort(mills: Long): String = unused()
    override fun timeString(): String = unused()
    override fun timeString(mills: Long): String = unused()
    override fun secondString(): String = unused()
    override fun secondString(mills: Long): String = unused()
    override fun minuteString(): String = unused()
    override fun minuteString(mills: Long): String = unused()
    override fun hourString(): String = unused()
    override fun hourString(mills: Long): String = unused()
    override fun amPm(): String = unused()
    override fun amPm(mills: Long): String = unused()
    override fun dayNameString(format: String): String = unused()
    override fun dayNameString(mills: Long, format: String): String = unused()
    override fun dayString(mills: Long): String = unused()
    override fun monthString(format: String): String = unused()
    override fun monthString(mills: Long, format: String): String = unused()
    override fun weekString(): String = unused()
    override fun weekString(mills: Long): String = unused()
    override fun timeStringWithSeconds(mills: Long): String = unused()
    override fun dateAndTimeRangeString(start: Long, end: Long): String = unused()
    override fun timeRangeString(start: Long, end: Long): String = unused()
    override fun dateAndTimeString(mills: Long): String = unused()
    override fun dateAndTimeStringNullable(mills: Long?): String? = unused()
    override fun dateAndTimeAndSecondsString(mills: Long): String = unused()
    override fun minAgo(rh: TextResolver, time: Long?): String = unused()
    override fun minOrSecAgo(rh: TextResolver, time: Long?): String = unused()
    override fun minOrSec(rh: TextResolver, durationMs: Long): String = unused()
    override fun minAgoShort(time: Long?): String = unused()
    override fun minAgoLong(rh: TextResolver, time: Long?): String = unused()
    override fun hourAgo(time: Long, rh: TextResolver): String = unused()
    override fun dayAgo(time: Long, rh: TextResolver, round: Boolean): String = unused()
    override fun beginOfDay(mills: Long): Long = unused()
    override fun timeStringFromSeconds(seconds: Int): String = unused()
    override fun timeFrameString(timeInMillis: Long, rh: TextResolver, withParentheses: Boolean): String = unused()
    override fun sinceString(timestamp: Long, rh: TextResolver): String = unused()
    override fun untilString(timestamp: Long, rh: TextResolver, withParentheses: Boolean): String = unused()
    override fun timeRemainingString(timeInMillis: Long, rh: TextResolver): String = unused()
    override fun now(): Long = aimiWallClockMs()
    override fun nowWithoutMilliseconds(): Long = unused()
    override fun isOlderThan(date: Long, minutes: Long): Boolean = unused()
    override fun getTimeZoneOffsetMs(): Long = unused()
    override fun getTimeZoneOffsetMsWithDST(): Long = unused()
    override fun getTimeZoneOffsetMinutes(timestamp: Long): Int = unused()
    override fun isSameDay(timestamp1: Long, timestamp2: Long): Boolean = unused()
    override fun isAfterNoon(): Boolean = unused()
    override fun isSameDayGroup(timestamp1: Long, timestamp2: Long): Boolean = unused()
    override fun computeDiff(date1: Long, date2: Long): TimeDiff = unused()
    override fun age(milliseconds: Long, useShortText: Boolean, rh: TextResolver): String = unused()
    override fun niceTimeScalar(time: Long, rh: TextResolver): String = unused()
    override fun qs(x: Double, numDigits: Int): String = unused()
    override fun formatHHMM(timeAsSeconds: Int): String = unused()
    override fun timeZoneByOffset(offsetInMilliseconds: Long): String = unused()
    override fun timeStampToUtcDateMillis(timestamp: Long): Long = unused()
    override fun getTimestampWithCurrentTimeOfDay(timestamp: Long): Long = unused()
    override fun mergeUtcDateToTimestamp(timestamp: Long, dateUtcMillis: Long): Long = unused()
    override fun mergeHourMinuteToTimestamp(timestamp: Long, hour: Int, minute: Int, randomSecond: Boolean): Long = unused()
}
