name: Build AAPS Full + Wear

on:
  workflow_dispatch:
    inputs:
      buildVariant:
        description: 'Build Type'
        required: true
        default: 'Release'
        type: choice
        options: [Release, Debug]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Decode Secrets
        run: |
          DECODED=$(echo "${{ secrets.KEYSTORE_SET }}" | base64 -d)
          echo "KEY_BASE64=$(echo "$DECODED" | cut -d'|' -f1)" >> $GITHUB_ENV
          echo "K_PASS=$(echo "$DECODED" | cut -d'|' -f2)" >> $GITHUB_ENV
          echo "K_ALIAS=$(echo "$DECODED" | cut -d'|' -f3)" >> $GITHUB_ENV
          echo "K_ALIAS_PASS=$(echo "$DECODED" | cut -d'|' -f4)" >> $GITHUB_ENV
          echo "GDRIVE_OAUTH2=${{ secrets.GDRIVE_OAUTH2 }}" >> $GITHUB_ENV

      - name: Decode Keystore
        run: |
          mkdir -p "$RUNNER_TEMP/keystore"
          echo "$KEY_BASE64" | base64 -d > "$RUNNER_TEMP/keystore/keystore.jks"

      - name: Build Full & Wear
        run: |
          chmod +x gradlew
          ./gradlew :app:assembleFull${{ github.event.inputs.buildVariant }} \
                    :wear:assembleFull${{ github.event.inputs.buildVariant }} \
            --no-daemon --max-workers=2 -Dorg.gradle.jvmargs="-Xmx5g" \
            -Pandroid.injected.signing.store.file="$RUNNER_TEMP/keystore/keystore.jks" \
            -Pandroid.injected.signing.store.password="$K_PASS" \
            -Pandroid.injected.signing.key.alias="$K_ALIAS" \
            -Pandroid.injected.signing.key.password="$K_ALIAS_PASS"

      - name: Rename and Upload
        # [Naming logic: Full-Version-Variant_Date.apk]
        run: |
          mkdir -p out
          VERSION=$(grep 'val appVersion' buildSrc/src/main/kotlin/Versions.kt | awk -F '"' '{print $2}')
          find . -name "*.apk" | while read -r file; do
            TYPE="Full"; [[ "$file" == *"wear"* ]] && TYPE="Wear"
            NAME="${TYPE}-${VERSION}-${{ github.event.inputs.buildVariant }}_$(date +'%Y%m%d').apk"
            cp "$file" "out/$NAME"
          done
      
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: AAPS-Main-Build
          path: out/*.apk
